apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-deployment
  labels:
    app: payment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
        - name: payment
          image: sojansm/paymentsapi:eks
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "250m"
