apiVersion: v1
kind: Service
metadata:
  name: payment-service
  labels:
    name: payment
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      nodePort: 30000
      name: http
  selector:
    app: payment
